### ISSUE TITLE
RowMapper can not be sent as lambda for method SQLBuilder.getMap 

### ISSUE THREAD

**Issue by prasad-babu** [MetricStream/SQLBuilder#1]
Now we cannot send rowmapper lambda as overloaded method (without boolean `withNull` parameter) is removed, 
We were able to send rowmapper before as below
`.getMap(conn) { rs -> SQLBuilder.entry(rs.getString(1), rs.getString(2)) }`

This is breaking backward compatibility

**Comment by nkiesel** [comment]
can you please tell exactly which version of SQLBuilder this issue is reported for? The current version 3.6.1 contains `com.metricstream.jdbc.SQLBuilderTest#map_test1` (see https://github.com/MetricStream/SQLBuilder/blob/41a31775f87a22cdd3bb5b2018ef00c3da954c99/mock/src/test/java/com/metricstream/jdbc/SQLBuilderTest.kt#L587) which does exactly that. The same exists for Java calls at  https://github.com/MetricStream/SQLBuilder/blob/41a31775f87a22cdd3bb5b2018ef00c3da954c99/mock/src/test/java/com/metricstream/jdbc/SQLBuilderTestJava.java#L568

**Comment by nkiesel** [comment]
I think I see the issue: the optional `withNull` is after the lambda.  Try using `.getMap(conn, { rs -> SQLBuilder.entry(rs.getString(1), rs.getString(2)) })` as a workaround for now (i.e. move the lambda inside the `()`.

**Comment by nkiesel** [comment]
Released version `3.7.0` which fixes this regression. Thanks for reporting!
